name: "Autojade Test Runner"
description: "Run Playwright tests using Autojade's managed test service"
inputs:
  api_key:
    description: "API Key to authenticate with Autojade."
    required: true
  test_files:
    description: "Test files or directory to upload (default: tests)."
    default: "tests"  # Default to the 'tests' folder
    required: false
  options:
    description: "Optional execution options."
    required: false
runs:
  using: "node20"  # Specify Node.js 20 here
  main: "dist/index.js"
