name: Test Autojade Action
on: 
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run Playwright Tests with Autojade (Custom Folder)
      uses: dotjade/autojade-action@main
      with:
        api_key: ${{ secrets.AUTOJADE_API_KEY }}
        test_files: "sample_tests/custom_tests"
        options: "--headless"
